%% AE 410 Assignment -2
% Submitted by : Ram Milan Verma; 150010037
%% Q2.(c) Deviated Pursuit Guidance
% plots for delta =10,20,30 can be generated by just changing the delta variable below
clear; close all;
gamaT=120; VT=300; VM=500;
delta=30; % deviation
r(1)=10000; %initial r
theta(1)=30; % initial theta
Vr0=VT*cosd(gamaT-theta(1))-VM*cosd(delta);
V_theta0=VT*sind(gamaT-theta(1))-VM*sind(delta);
tf=r(1)*(Vr0+2*VM*cosd(delta)-V_theta0*tand(delta))/(VM^2-VT^2); % time of collision
dt=1e-3;  % integration time step
Ns=floor(tf/dt); % number of samples
t=linspace(0,tf,Ns);
xM(1)=0; yM(1)=0; %missile's initial coordinate assumed to (0,0) WLOG
xT(1)=r(1)*cosd(30); yT(1)=r(1)*sind(30); % initial position of target w.r.t. missile
for i=1:Ns
    % rate calculatio step
    rdot= VT*cosd(gamaT-theta(i)) - VM*cosd(delta);
    theta_dot=(VT*sind(gamaT-theta(i))-VM*sind(delta))/r(i); %rad / sec
    aM(i)=VM*theta_dot;
    % update step
    r(i+1)=r(i) + rdot*dt;
    theta(i+1)=theta(i) + theta_dot*dt*180/pi;
    xM(i+1)=xM(i)+ VM*cosd(theta(i+1)+delta)*dt;
    yM(i+1)=yM(i)+ VM*sind(theta(i+1)+delta)*dt;
    xT(i+1)=xT(i)+ VT*cosd(gamaT)*dt;
    yT(i+1)= yT(i)+VT*sind(gamaT)*dt;
end
% plotting of trajectory and guidance command
figure
plot(xM,yM,xT,yT), xlabel('x(in m)'),ylabel('y(in m)'),legend('missile', 'target'), title('trajectory'), grid on
suptitle(strcat('For delta= ',num2str(delta),'^o' ))
annotation('textbox', [0.5, 0.2, 0.1, 0.1], 'String',strcat('tf= ',num2str(tf), ' sec'));
dim = [.1 .4 .2 .2];
str = strcat('collision @ x= ',num2str(xM(i)),' ,y= ',num2str(yM(i)));
annotation('textbox',dim,'String',str,'FitBoxToText','on');
figure
plot(t,aM),xlabel('time(sec)'),ylabel('Missile acceleration(m/sec^2)'),legend('aM'), title('Guidance command'); grid on
suptitle(strcat('For delta= ',num2str(delta),'^o' ))